version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "DocumentsSetTextract"
s3_bucket = "cyruswong-sam-repo"
s3_prefix = "DocumentsSetTextract"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
